version: '3.9'

services:
  mongo:
    image: mongo
    container_name: mongodb
    restart: always
    ports:
      - '27017:27017'
    volumes:
      - mongo-data:/data/db

  backend:
    build: .
    container_name: task-manager-api
    restart: always
    ports:
      - '5000:5000'
    environment:
      - PORT=5000
      - MONGO_URI=mongodb://mongo:27017/taskmanager
      - JWT_SECRET=supersecretkey
    depends_on:
      - mongo
    volumes:
      - .:/usr/src/app

volumes:
  mongo-data:
